server:
  port: 8888
spring:
  profiles.active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.132.137.156:3306/lmx?multiStatement=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=CTT
    username: root
    password: lmx@123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 3000000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，加了wall 无法批量更新
    filters: stat,log4j
    logSlowSql: true
  resources:
        staticLocations:classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  redis:
    host: 101.132.137.156
    port: 6380
    password: lmx123456@
    jedis:
      pool:
        max-active: 20
        min-idle: 0
    timeout: 10000s
    database: 1
  rabbitmq:
    host: 101.132.137.156
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
  data:
    elasticsearch:
      cluster-name: docker-cluster    # 本地docker集群名称
      cluster-nodes: localhost:9300   # 集群节点
      repositories:
        enabled: true    # 是否开启本地存储
#  email:
#    host: smtp.qq.com
#    username: 710285449@qq.com
#    password: hngtswgqlxyabdbb
#    default-encoding: UTF-8
#    port: 587
mail:
  fromMail:
    addr: 710285449@qq.com
#  data:
#      elasticsearch:
#        # es 集群名称
#        cluster-name: blog
#          # es 节点地址
#        cluster-nodes: 101.132.137.156:9300
#        # 是否开启本地存储
#        repositories:
#          enabled: true
logging:
    config: classpath:logback.xml
mybatis:
  mapper-locations: classpath:mybatis-config.xml
  type-aliases-package: com.lmx.log.mapper
api:
  ipUrl: http://apis.juhe.cn/ip/ipNew?ip=
  key: 64b89e1f7ec763888eb2505936e5a24a
#rocketmq:
#  name-server: ${ROCKET_NAMESERVER}
#  producer:
#    group: ${ROCKETMQ_PRODUCER_GROUP_ID}
#    access-key: ${ROCKETMQ_ACCESS_KEY}
#    secret-key: ${ROCKETMQ_SECRET_KEY}
#    enable-msg-trace: false
#    send-message-timeout: 10000
#  consumer:
#    access-key: ${ROCKETMQ_ACCESS_KEY}
#    secret-key: ${ROCKETMQ_SECRET_KEY}


